### ISSUE TITLE
Salvadoran colón has wrong currency symbol

### ISSUE THREAD

**Issue by sweaver360** [panosl/django-currencies#21]
I know El Salvador uses USD now, but according to Wikipedia, the old Salvadoran colón uses ₡ rather than $.

http://en.wikipedia.org/wiki/Salvadoran_col%C3%B3n

Not really that big of a deal, but figured I'd let you know.

**Comment by racitup** [comment]
Checkout [my fork](https://github.com/racitup/django-currencies) - the Yahoo backend has the correct symbol :-)

**Comment by einarf** [comment]
You can tweak that in : https://github.com/panosl/django-currencies/blob/master/currencies/management/commands/currencies.json

**Comment by panosl** [comment]
Thanks, fixed!
