### ISSUE TITLE
Merging with django-simple-currencies fork

### ISSUE THREAD

**Issue by bashu** [panosl/django-currencies#22]
Hey,

Can you check my fork here https://github.com/bashu/django-simple-currencies

Notable changes are : using middleware instead of context processor, works with site-wide caching, improved management commands and a lot of clean up

If this changes are okey for you I can backport them via "pull requests" or you can add me as collabarator

**Comment by panosl** [comment]
Wow, sorry to keep you waiting that long mate, I've disabled mail notifications and totally missed this one!

I could use help with maintaining currencies, as I'm really spread thin between projects, so if you're interested let me know.

**Comment by bashu** [comment]
Yes sure I can help with maintaining currencies

**Comment by panosl** [comment]
Great! I've added you as a collaborator. Please do not backport middleware etc, yet. Start from current open issues and pull requests, after that we can talk about which features can be backported.

**Comment by mafrosis** [comment]
Any progress on this guys? We need to add some caching for all the DB queries and were considering a fork. It would be great to be able to contribute to something useable by others.

**Comment by bashu** [comment]
Hey, I will "fix" that on weekend

**Comment by mafrosis** [comment]
:+1: Let me know if there is anything I can do to help

**Comment by panosl** [comment]
That's good news :)

On Fri, Sep 25, 2015 at 6:13 PM, Matt Black <notifications@github.com>
wrote:

> [image: :+1:] Let me know if there is anything I can do to help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/panosl/django-currencies/issues/22#issuecomment-143249102>
> .
>



-- 
Panos Laganakos
http://panoslaganakos.com

**Comment by einarf** [comment]
You should get the develop branch down in master asap. Right now the state of what is in master is getting way too outdated and there are compatibility issues out of the box unless you are still using Django 1.5.x :)

**Comment by panosl** [comment]
Merged the develop branch into master, just checking stuff and will put a release out to PyPI.
