### ISSUE TITLE
Where is currencies.util.calculate_price?

### ISSUE THREAD

**Issue by ZzAntares** [panosl/django-currencies#37]
Hi, I'm just upgrading dependencies in one of my project, I notice the function `currencies.utils.calculate_price` is gone, I depend on this to do some currency conversion in a backend process.

I have tracked the deletion up to this commit 39b785a from @bashu, and I notice there's now a `currencies.utils.calculate` is that the same function that just got renamed? The commit message isn't helpful at all, it doesn't explain the changes that were made.

Thanks for the help!

**Comment by einarf** [comment]
Yep. That should be the new function. A lot of things were rewritten in this version, so things like that is to be expected.

**Comment by panosl** [comment]
@einarf is right, that is the same function with a signature change, and the logic a bit squeezed :D Other than that it works the same.

@bashu rewrote and repositioned major parts of the code, so yeah, things like that are to be expected, but it's for the best!

I hope it's just a minor inconvenience, feel free point out anything else we missed.

**Comment by ZzAntares** [comment]
Thanks for the clarification, I needed to be sure, I've updated my old references everything seems to work as always.

Thanks!
