### ISSUE TITLE
better OpenExchangeRates error reporting

### ISSUE THREAD

**Issue by robmoggach** [panosl/django-currencies#38]
Changing the base currency from USD to some other currency requires a paid account with OpenExchangeRates.  

Currently the API returns an error that doesn't make this clear at first glance:

```
openexchangerates.OpenExchangeRatesClientException: 
403 Client Error: Forbidden for url: http://openexchangerates.org/
api/latest.json?app_id=xxxxxxxxxxxxxxx&base=GBP
```

Copying the request URL to another tab reveals the problem but this exception should be handled appropriately.

**Comment by racitup** [comment]
Should now be fixed on my fork which has completely restructured the management commands to integrate other sources. Yahoo Finance now integrated. [Check it out!](https://github.com/racitup/django-currencies)

I am just going to raise a pull request :-)

**Comment by bashu** [comment]
@racitup +1 for PR

**Comment by einarf** [comment]
@racitup @bashu I wonder if you might be better off just moving the actual openexchangerates module into this project. It seems to be abandoned and do not support python 3 because of this bug that has a PR waiting for almost a year metglobal/openexchangerates#6

**Comment by panosl** [comment]
Show me the pull requests :)

**Comment by racitup** [comment]
See PR #43 :)
