### ISSUE TITLE
Unique code causes conflict

### ISSUE THREAD

**Issue by dariemp** [panosl/django-currencies#51]
When migrating to django-currencies 0.4.0, new entries for HKD and ZAR currency codes where included which causes duplication in the database. Old enties for HKD and ZAR were marked as is_active=False, but this doesn't solve the issue because code is not unique. Uggly solution is to use SQL to remove inactive entries but this should be address with Django migrations.

**Comment by racitup** [comment]
This should be fixed in #54. The latest code uses the currency code as primary key so it's not possible to have duplicates

**Comment by panosl** [comment]
0.9.0 has been released both here and on PyPI. Marking this as fixed.
