### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by stevelacey** [panosl/django-currencies#54]
Looks like there's been a fair few commits since 0.4.0, bump the version? Appears the `updatecurrencies` command in 0.4.0 doesn't work on Django 1.10.

**Comment by einarf** [comment]
Yes. A new version is definitely needed. I've been installing from a fork here on github for a long time to freeze the master branch.

**Comment by racitup** [comment]
Is there anything stopping a new version?

**Comment by panosl** [comment]
@racitup you seem to be doing a good job on keeping things up to date. Reach out to me, if you'd be willing to handle the next release.

**Comment by racitup** [comment]
Hey, thanks! Unfortunately it seems my yahoo 'integration' (read: scrape) has broken because yahoo changed their site. I'll need to fix this really.

Also it looks like someone had a go with Travis CI which would be a great idea for testing new Django & python versions... I haven't seen the build status check thing for PRs though. Does anyone have expertise in Travis CI?

**Comment by panosl** [comment]
I'll try to set up travis-ci but all the tests are currently broken, I merged some of @racitup pull requests, but we need to test things further to push out a version on PyPI.

**Comment by racitup** [comment]
Thanks for merging everything. I need to get back to this because I've been neglecting stuff.
I should also really look at adding tests for the various currency source integrations. I assume the tests.py is compatible with Travis?

**Comment by einarf** [comment]
The version in master is now 0.4.0, but releases (https://github.com/panosl/django-currencies/releases) claims this version was released May 17, 2016. Can you clean that up to cause less confusion?

Either add releases consistently or just remove them all relying on master branch 😄

**Comment by panosl** [comment]
> Thanks for merging everything. I need to get back to this because I've been neglecting stuff.
> I should also really look at adding tests for the various currency source integrations. I assume the tests.py is compatible with Travis?

@racitup as I mentioned earlier, the tests are currently broken, I've set up a travis-ci but we need to fix these first.

@einarf Yup we'll bump the version number soon. The functionality is there, if we clean thing up we might be reaching 1.0 soon.

I have some time now  since I'm in between projects, so it'll be great if we can put things together so we can push out a new release out there. All help is welcome!

**Comment by racitup** [comment]
Is there a description for what 1.0 should be?

**Comment by panosl** [comment]
> Is there a description for what 1.0 should be?

@racitup We have more than enough functionality as it is right now. The thing that we're missing most is testing. Other than that we don't need to work on any added features for now.

After that we can push 0.9 out see if we get any bug reports and finalize the 1.0.

**Comment by racitup** [comment]
So it seems the tests fail because they can't find the test_data fixture.
Since it makes sense for the tests and fixtures to stay together, should we move the tests package to the example project?

**Comment by panosl** [comment]
@racitup Not really. I was thinking we could drop the example project. The project and documentation are pretty clear, and we don’t need the maintainace overhead. Tests, should be able to be run from without the example project.

**Comment by racitup** [comment]
I've made a pull request with tests now passing with django >= 1.8
It seems the jsonfield used for the info field does not support older versions of django. Do we need to support these?

> error: Django 1.4.22 is installed but Django>=1.8.0 is required by set(['jsonfield'])

**Comment by panosl** [comment]
Awesome work! No, if people need to use older versions of Django, they can stick to an older currencies version as well.

**Comment by racitup** [comment]
Cool, I'll add in the build status ([![Build Status](https://travis-ci.org/panosl/django-currencies.svg?branch=master)](https://travis-ci.org/panosl/django-currencies)) and remove django 1.4.22 then.
Then I want to implement a load of tests for the management commands (especially yahoo which has ceased).
Then I'll fix yahoo somehow (deprecation warning & possibly disable)
Then I might even implement an ECB currency source
Then I think we'll be ready to roll!

**Comment by panosl** [comment]
That’s great mate, i appreciate your efforts so much ! Ping me if you need anything.

Στάλθηκε από το iPhone μου

14 Νοε 2018, 3:14 μμ, ο χρήστης «racitup <notifications@github.com>» έγραψε:

**Comment by panosl** [comment]
We're proud to show ([![Build Status](https://travis-ci.org/panosl/django-currencies.svg?branch=master)](https://travis-ci.org/panosl/django-currencies)) ladies and gentlemen!

**Comment by racitup** [comment]
Do you have an openexchangerates API key for testing? The one in the README works for currencies but not the rates

**Comment by racitup** [comment]
Please merge in #66 when you get a chance. Should be ready to roll now. Would be interesting to get codecov going too. I've added it to the dependencies. Then I have another branch ready to merge after that one with version 0.9.0 on it 😊

**Comment by panosl** [comment]
Awesome work @racitup ! You brought the heat again <3

I've given you write access to the repo, so if I'm not responding, you have authority to do your amazing thing :)

**Comment by racitup** [comment]
Thanks @panosl,
#67 Now integrates all the changes I think we needed. I didn't add ecb in the end, but we do now have codecov integration which I think is much more important!
The last things to do I think are:
- sign up for codecov.io which should get the badge working
- update the docs
- remove the example if you feel like it. I don't think anything is used there now and it's looking quite dated
- remove south migrations (integrated into django v1.7) and landscape.yaml?

**Comment by panosl** [comment]
Yup, sounds like a plan. I think we can just call this 1.0. It's been production ready for years now, this is much more with the cleanup and functionality you added :)

**Comment by panosl** [comment]
Ok, I removed the south migrations and the dated example.

**Comment by racitup** [comment]
Sweet! Looks much cleaner and we hit 90% coverage :)

**Comment by panosl** [comment]
Yay! Let's get this thing out there and see  if we can set a plan for the next major milestone :D

**Comment by racitup** [comment]
How about we tag and release this as 0.9.0 and leave it a week or two to see if there are any issues?
There's a small tweak that's been bugging me which is to move the currency file caching into the parent CurrencyHandler class which will make it functional for oxr, and I can simplify the tests a bit too...

**Comment by panosl** [comment]
Alright, I'll tag it and upload on PyPI etc.

**Comment by panosl** [comment]
@racitup Done, it's public both on GitHub and PyPI. Had a minor glitch with the classifiers, but it's all good!

Thanks for making this a fantastic release! Take your time and we'll talk soon about what we might need to address for 1.0.0

**Comment by racitup** [comment]
Mmm, I think just remove that classifier.. looks like the Travis build is failing because of it (which is weird)

**Comment by panosl** [comment]
Nah, it was just travis-ci being stuck. All is good now: https://travis-ci.org/panosl/django-currencies

It was trying to download the pypy3 version but it wasn't available for some reason. Nothing on our end.

**Comment by einarf** [comment]
Awesome work getting a new release out. You even created a ``whl`` and addad `0.9` tag. I'm guessing a lot of people can delete their own forks now. 👍
