### ISSUE TITLE
set_currency view error

### ISSUE THREAD

**Issue by wierzcho** [panosl/django-currencies#71]
I had an error trying to change `{{ CURRENCY }}` and `{{ CURRENCY_CODE }}` template variables via post method. 
Variables could not be changed unless I changed 
`request.POST.get('currency_code, None)` and `request.GET.get('currency_code', None)` 
to 
`request.POST.get('currency', None)` and `request.GET.get('currency', None)`.
Dunno if this is error determined by my local settings or general bug.

This is how the code should look like to make it work:

```
@never_cache
def set_currency(request):
    next, currency_code = (
        request.POST.get('next') or request.GET.get('next'),
        request.POST.get('currency', None) or
        request.GET.get('currency', None))
    if not _is_safe_url(next, [request.get_host()]):
        next = request.META.get('HTTP_REFERER')
        if not _is_safe_url(next, [request.get_host()]):
            next = '/'

    response = HttpResponseRedirect(next)
    if currency_code and Currency.active.filter(code=currency_code).exists():
        # Set cookie irrespective for page cache visibility
        response.set_cookie(SESSION_KEY, currency_code)
        if hasattr(request, 'session'):
            request.session[SESSION_KEY] = currency_code
    return response
```

**Comment by racitup** [comment]
Hi, could you be more explicit with what you're trying to do and what the error message is please?
You don't really change the template variables directly, that view changes the value stored in the cookie and session, which then will flow through to subsequent requests.
There is an example in the templates on how to construct the url.

**Comment by panosl** [comment]
No feedback was provided, so we're closing this.
