### ISSUE TITLE
Data too long for column 'name' at row 1

### ISSUE THREAD

**Issue by pasevin** [panosl/django-currencies#72]
```python manage.py currencies``` fails with: ```MySQLdb._exceptions.DataError: (1406, "Data too long for column 'name' at row 1")```

**Comment by racitup** [comment]
Please can you be more specific with what you're trying to do, what version of django, the module version you have reported by pip and where you installed it from?

**Comment by einarf** [comment]
Maybe creating issue templates could be an idea? Need to do that for a couple of my projects as well when I think of it.

**Comment by pasevin** [comment]
Sorry if it was not clear enough.

I was trying to use management command ```python manage.py currencies``` to populate my DB with up to date currencies from OPENEXCHANGERATES. It kept updating my DB with no problem until it reached some currency which name appeared too long for the field 'name'. This is where it crashed.

Module version is the latest 0.9.0.
Django 2.1.10

**Comment by pasevin** [comment]
Looks like the current ```name``` varchar limitation of 35 characters is too small for some currency names.

**Comment by pasevin** [comment]
This PR fixes it: https://github.com/panosl/django-currencies/pull/74
